# Generated by Django 4.1.7 on 2023-03-27 15:07

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_birth_date_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[accounts.validators.PhoneValidator()], verbose_name='phone'),
        ),
    ]
