# Generated by Django 4.1.7 on 2023-04-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Product color', 'verbose_name_plural': 'Product colors'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Product size', 'verbose_name_plural': 'Product sizes'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub category', 'verbose_name_plural': 'Sub categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.productcolor', verbose_name="Product's color"),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.productsize', verbose_name="Product's size"),
        ),
    ]
