# Generated by Django 4.1.7 on 2023-06-10 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_product_description_en_product_description_fa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('number_of_likes', models.PositiveIntegerField(default=0, verbose_name='Number of likes')),
                ('number_of_dislikes', models.PositiveIntegerField(default=0, verbose_name='Number of dislikes')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created datetime')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Modified datetime')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('star_rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')], verbose_name='Star rating')),
                ('suggestion', models.PositiveSmallIntegerField(choices=[(1, 'I suggest'), (2, "I don't suggest"), (3, "I'm not sure")], default=0, verbose_name='Suggestion')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Is anonymous?')),
                ('number_of_likes', models.PositiveIntegerField(default=0, verbose_name='Number of likes')),
                ('number_of_dislikes', models.PositiveIntegerField(default=0, verbose_name='Number of dislikes')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created datetime')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Modified datetime')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
