# Generated by Django 4.1.7 on 2023-07-08 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_remove_comment_number_of_dislikes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created datetime')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Modified datetime')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='products.product', verbose_name='Product')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='products.question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='AnswerDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Modified datetime')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='products.answer', verbose_name='Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Answer dislike',
                'verbose_name_plural': 'Answer dislikes',
            },
        ),
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Modified datetime')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='products.answer', verbose_name='Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_likes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Answer like',
                'verbose_name_plural': 'Answer likes',
            },
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='commentdislike',
            options={'verbose_name': 'Comment dislike', 'verbose_name_plural': 'Comment dislikes'},
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'Comment like', 'verbose_name_plural': 'Comment likes'},
        ),
        migrations.DeleteModel(
            name='QuestionDislike',
        ),
        migrations.DeleteModel(
            name='QuestionLike',
        ),
    ]
